[project]
name = "now-playing-api"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[all]>=0.116.1",
    "pycaw>=20240210",
    "pydantic>=2.11.7",
    "pywin32>=311",
]
